# Generated by Django 3.2.8 on 2021-10-06 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('tag', models.CharField(choices=[('wallpapers', 'wallpapers'), ('places', 'places'), ('beauty', 'beauty'), ('village', 'village'), ('Technology', 'Technology'), ('Abstract', 'Abstract'), ('Animals', 'Animals'), ('Drinks', 'Drinks,'), ('Entertainment', 'Entertainment'), ('Food', 'Food'), ('Holidays', 'Holidays'), ('People', 'People'), ('Sports', 'Sports'), ('Vehicles', 'Vehicles'), ('World', 'World'), ('Other', 'Other')], max_length=50)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
