# Generated by Django 3.2.4 on 2021-08-10 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('DOB', models.DateField()),
                ('password', models.CharField(max_length=20)),
                ('confirm_password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
                ('tag', models.CharField(choices=[('wallpapers', 'wallpapers'), ('places', 'places'), ('animals', 'animals'), ('beauty', 'beauty'), ('village', 'village'), ('tech', 'tech')], max_length=50)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
